title: National Crime Prevention Council
url: https://ncpc.org.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#71011b"
  secondary-color: "#a20427"
  media-colors:
    - title: media-color-one
      color: "#71011b"
    - title: media-color-two
      color: "#a20427"
    - title: media-color-three
      color: "#71011b"
    - title: media-color-four
      color: "#71011b"
    - title: media-color-five
      color: "#71011b"
description: National Crime Prevention Council is a non-profit organization
  committed to promoting public awareness of and concern about crime and to
  propagate the concept of self-help in crime prevention.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2lbmnnayfe7jh.amplifyapp.com
prod: https://master.d2lbmnnayfe7jh.amplifyapp.com
resources_name: news-and-events
shareicon: /images/logo-ncpc2.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
google_analytics_ga4: ""
